USE [master]
GO
/****** Object:  Database [dapperdev]    Script Date: 05/04/2024 0:28:55 ******/
CREATE DATABASE [dapperdev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dapperdev', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\dapperdev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dapperdev_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\dapperdev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [dapperdev] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dapperdev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dapperdev] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dapperdev] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dapperdev] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dapperdev] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dapperdev] SET ARITHABORT OFF 
GO
ALTER DATABASE [dapperdev] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dapperdev] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dapperdev] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dapperdev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dapperdev] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dapperdev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dapperdev] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dapperdev] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dapperdev] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dapperdev] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dapperdev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dapperdev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dapperdev] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dapperdev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dapperdev] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dapperdev] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dapperdev] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dapperdev] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [dapperdev] SET  MULTI_USER 
GO
ALTER DATABASE [dapperdev] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dapperdev] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dapperdev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dapperdev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [dapperdev] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dapperdev] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [dapperdev] SET QUERY_STORE = ON
GO
ALTER DATABASE [dapperdev] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [dapperdev]
GO
/****** Object:  Table [dbo].[authors]    Script Date: 05/04/2024 0:28:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[authors](
	[AuthorId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
 CONSTRAINT [PK_authors] PRIMARY KEY CLUSTERED 
(
	[AuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[books]    Script Date: 05/04/2024 0:28:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[books](
	[BookId] [bigint] IDENTITY(1,1) NOT NULL,
	[PersonId] [bigint] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Description] [nvarchar](100) NULL,
	[PagesNumber] [int] NOT NULL,
	[IdAuthor] [bigint] NULL,
 CONSTRAINT [PK_books] PRIMARY KEY CLUSTERED 
(
	[BookId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[items]    Script Date: 05/04/2024 0:28:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[items](
	[ItemId] [bigint] NOT NULL,
	[PersonId] [bigint] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Description] [nvarchar](100) NULL,
 CONSTRAINT [PK_items] PRIMARY KEY CLUSTERED 
(
	[ItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[persons]    Script Date: 05/04/2024 0:28:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[persons](
	[PersonId] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
 CONSTRAINT [PK_persons] PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[books] ADD  CONSTRAINT [DF_books_PagesNumber]  DEFAULT ((0)) FOR [PagesNumber]
GO
ALTER TABLE [dbo].[books]  WITH CHECK ADD  CONSTRAINT [FK_books_authors] FOREIGN KEY([IdAuthor])
REFERENCES [dbo].[authors] ([AuthorId])
GO
ALTER TABLE [dbo].[books] CHECK CONSTRAINT [FK_books_authors]
GO
ALTER TABLE [dbo].[books]  WITH CHECK ADD  CONSTRAINT [FK_books_persons] FOREIGN KEY([PersonId])
REFERENCES [dbo].[persons] ([PersonId])
GO
ALTER TABLE [dbo].[books] CHECK CONSTRAINT [FK_books_persons]
GO
ALTER TABLE [dbo].[items]  WITH CHECK ADD  CONSTRAINT [FK_items_persons] FOREIGN KEY([PersonId])
REFERENCES [dbo].[persons] ([PersonId])
GO
ALTER TABLE [dbo].[items] CHECK CONSTRAINT [FK_items_persons]
GO
USE [master]
GO
ALTER DATABASE [dapperdev] SET  READ_WRITE 
GO
